name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Python kurulumu
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Flask
        run: pip install flask

      - name: Start Flask server
        run: python WebPanelApp/app.py &
        shell: bash

      - name: Wait for Flask server to start
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Waiting for Flask server..."
            sleep 2
          done
        shell: bash

      # .NET kurulumu
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore WebPanelTest/WebPanelTest/WebPanelTest.csproj

      - name: Build test project
        run: dotnet build WebPanelTest/WebPanelTest/WebPanelTest.csproj --configuration Debug

      - name: Run tests and generate TRX log
        run: dotnet test WebPanelTest/WebPanelTest/WebPanelTest.csproj --logger "trx;LogFileName=test-results.trx"

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate HTML report
        run: reportgenerator -reports:**/test-results.trx -targetdir:TestResultsReport -reporttypes:Html
        env:
          PATH: ${{ env.PATH }};C:\Users\runneradmin\.dotnet\tools

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: TestResultsReport
