name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t webpanel-image -f Dockerfile .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name webpanel-container webpanel-image

      - name: Wait for Flask app to be ready
        run: |
          echo "Checking if Flask app is ready..."
          for i in {1..15}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "Flask app is reachable!"
              break
            fi
            echo "Waiting for Flask app..."
            sleep 2
          done

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore WebPanelTest/WebPanelTest/WebPanelTest.csproj

      - name: Build test project
        run: dotnet build WebPanelTest/WebPanelTest/WebPanelTest.csproj --configuration Debug

      - name: Run tests and generate TRX log
        run: dotnet test WebPanelTest/WebPanelTest/WebPanelTest.csproj --logger "trx;LogFileName=test-results.trx"

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate HTML report
        run: reportgenerator -reports:**/test-results.trx -targetdir:TestResultsReport -reporttypes:Html
        env:
          PATH: ${{ env.PATH }}:/home/runner/.dotnet/tools

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: TestResultsReport
