name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'   # Kullandığın .NET versiyonuna göre değiştir

    - name: Restore dependencies
      run: dotnet restore WebPanelTest/WebPanelTest/WebPanelTest.csproj

    - name: Build solution
      run: dotnet build WebPanelTest/WebPanelTest/WebPanelTest.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test WebPanelTest/WebPanelTest/WebPanelTest.csproj --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"
